### ISSUE TITLE
ModuleNotFoundError: No module named 'socks_smtp'

### ISSUE THREAD

**Issue by taewookim** [Gardener-gg/email-verifier#6]
Python 3.7.3 on VirtualEnv
PySocks==1.7.1
dnspython==1.16.0

ideas?

**Comment by taewookim** [comment]
oh wait.. its a path issue.. sorry about that

**Comment by mbilal02** [comment]
Hello.
I am new in python and trying to use the socks_smtp.

I have installed the PySocks == 1.7.1 but getting the error 
from socks_smtp import SocksSMTP as SMTP
ModuleNotFoundError: No module named 'socks_smtp'

Can you please share what path you changed.

**Comment by LogFlames** [comment]
@mbilal02 You need to change
from socks_smtp import ...
to:
from verifier.socks_smtp import ...

The reason is that when the code is imported from your file, the path of that code is now your file.

your_file.py
verifier/
    verifier.py
    socks_smtp.py
    __init__.py
